export interface ProductCategory {
  id: number;
  imprimirRelat: string;
  aplicarAuto: string;
  codigo: string;
  descricao: string;
  desconto: string;
  valorDesconto: string;
  empresa: string;
  centroCusto: string;
  centroReceb: string;
}

export const mockProductCategories: ProductCategory[] = [
  {
    id: 1,
    imprimirRelat: 'REGISTRO 1',
    aplicarAuto: 'REGISTRO 1',
    codigo: 'REGISTRO 1',
    descricao: 'DESCRIÇÃO 1',
    desconto: 'REGISTRO 1',
    valorDesconto: 'REGISTRO 1',
    empresa: 'NOME DA EMPRESA 1',
    centroCusto: 'REGISTRO 1',
    centroReceb: 'REGISTRO 1',
  },
  {
    id: 2,
    imprimirRelat: 'REGISTRO 2',
    aplicarAuto: 'REGISTRO 2',
    codigo: 'REGISTRO 2',
    descricao: 'DESCRIÇÃO 2',
    desconto: 'REGISTRO 2',
    valorDesconto: 'REGISTRO 2',
    empresa: 'NOME DA EMPRESA 2',
    centroCusto: 'REGISTRO 2',
    centroReceb: 'REGISTRO 2',
  },
  {
    id: 3,
    imprimirRelat: 'REGISTRO 3',
    aplicarAuto: 'REGISTRO 3',
    codigo: 'REGISTRO 3',
    descricao: 'DESCRIÇÃO 3',
    desconto: 'REGISTRO 3',
    valorDesconto: 'REGISTRO 3',
    empresa: 'NOME DA EMPRESA 3',
    centroCusto: 'REGISTRO 3',
    centroReceb: 'REGISTRO 3',
  },
  {
    id: 4,
    imprimirRelat: 'REGISTRO 4',
    aplicarAuto: 'REGISTRO 4',
    codigo: 'REGISTRO 4',
    descricao: 'DESCRIÇÃO 4',
    desconto: 'REGISTRO 4',
    valorDesconto: 'REGISTRO 4',
    empresa: 'NOME DA EMPRESA 4',
    centroCusto: 'REGISTRO 4',
    centroReceb: 'REGISTRO 4',
  },
  {
    id: 5,
    imprimirRelat: 'REGISTRO 5',
    aplicarAuto: 'REGISTRO 5',
    codigo: 'REGISTRO 5',
    descricao: 'DESCRIÇÃO 5',
    desconto: 'REGISTRO 5',
    valorDesconto: 'REGISTRO 5',
    empresa: 'NOME DA EMPRESA 5',
    centroCusto: 'REGISTRO 5',
    centroReceb: 'REGISTRO 5',
  },
  {
    id: 6,
    imprimirRelat: 'REGISTRO 6',
    aplicarAuto: 'REGISTRO 6',
    codigo: 'REGISTRO 6',
    descricao: 'DESCRIÇÃO 6',
    desconto: 'REGISTRO 6',
    valorDesconto: 'REGISTRO 6',
    empresa: 'NOME DA EMPRESA 6',
    centroCusto: 'REGISTRO 6',
    centroReceb: 'REGISTRO 6',
  },
  {
    id: 7,
    imprimirRelat: 'REGISTRO 7',
    aplicarAuto: 'REGISTRO 7',
    codigo: 'REGISTRO 7',
    descricao: 'DESCRIÇÃO 7',
    desconto: 'REGISTRO 7',
    valorDesconto: 'REGISTRO 7',
    empresa: 'NOME DA EMPRESA 7',
    centroCusto: 'REGISTRO 7',
    centroReceb: 'REGISTRO 7',
  },
  {
    id: 8,
    imprimirRelat: 'REGISTRO 8',
    aplicarAuto: 'REGISTRO 8',
    codigo: 'REGISTRO 8',
    descricao: 'DESCRIÇÃO 8',
    desconto: 'REGISTRO 8',
    valorDesconto: 'REGISTRO 8',
    empresa: 'NOME DA EMPRESA 8',
    centroCusto: 'REGISTRO 8',
    centroReceb: 'REGISTRO 8',
  },
  {
    id: 9,
    imprimirRelat: 'REGISTRO 9',
    aplicarAuto: 'REGISTRO 9',
    codigo: 'REGISTRO 9',
    descricao: 'DESCRIÇÃO 9',
    desconto: 'REGISTRO 9',
    valorDesconto: 'REGISTRO 9',
    empresa: 'NOME DA EMPRESA 9',
    centroCusto: 'REGISTRO 9',
    centroReceb: 'REGISTRO 9',
  },
  {
    id: 10,
    imprimirRelat: 'REGISTRO 10',
    aplicarAuto: 'REGISTRO 10',
    codigo: 'REGISTRO 10',
    descricao: 'DESCRIÇÃO 10',
    desconto: 'REGISTRO 10',
    valorDesconto: 'REGISTRO 10',
    empresa: 'NOME DA EMPRESA 10',
    centroCusto: 'REGISTRO 10',
    centroReceb: 'REGISTRO 10',
  },
];
